// src/app/layout.js
import "./globals.css";

export const metadata = {
  title: "英単語・英熟語帳",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
